name: 'publish'

on:
  push:
    branches:
      - release
      - release-*
      - f2

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: 'macos-14'
            args: '--target aarch64-apple-darwin'
            build_type: 'release'
          - platform: 'macos-14'
            args: '--target aarch64-apple-darwin --debug'
            build_type: 'debug'
          - platform: 'macos-14'
            args: '--target x86_64-apple-darwin'
            build_type: 'release'
          - platform: 'macos-14'
            args: '--target x86_64-apple-darwin --debug'
            build_type: 'debug'
          - platform: 'ubuntu-22.04'
            args: ''
            build_type: 'release'
          - platform: 'ubuntu-22.04'
            args: '--debug'
            build_type: 'debug'
          - platform: 'windows-latest'
            args: ''
            build_type: 'release'
          - platform: 'windows-latest'
            args: '--debug'
            build_type: 'debug'

    runs-on: ${{ matrix.settings.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.settings.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
        # webkitgtk 4.0 is for Tauri v1 - webkitgtk 4.1 is for Tauri v2.
        # You can remove the one that doesn't apply to your app to speed up the workflow a bit.

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22.*

      - name: install pnpm
        run: npm install -g pnpm

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          # targets: ${{ matrix.settings.platform == 'macos-14' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
          toolchain: stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install frontend dependencies
        # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
        run: |
            rustc --version
            rustup target add x86_64-apple-darwin
            pnpm install # change this to npm or pnpm depending on which one you use.

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: golden-wallet-v__VERSION__-${{ matrix.settings.build_type }}
          releaseName: 'Golden Wallet v__VERSION__ (${{ matrix.settings.build_type }})'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.settings.args }}
